name: sage
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  another_flushbar: ^1.12.31-dev.1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_gen: ^5.10.0
  flutter_gen_runner: ^5.8.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.3
  flutter_svg: ^2.1.0
  # google_fonts: ^6.2.0
  http: ^1.2.2
  intl: any
  json_annotation: ^4.9.0
  pinput: ^5.0.1
  provider: ^6.1.5

dev_dependencies:
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  json_serializable: ^6.9.2
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/logo/
    - assets/images/dialog/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/static/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/Raleway/static/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Raleway/static/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway/static/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway/static/Raleway-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/static/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/static/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/static/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway/static/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Raleway/static/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway/static/Raleway-BlackItalic.ttf
          weight: 900
          style: italic

flutter_gen:
  output: lib/generated/assets
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo/launcher_icon.png"
  adaptive_icon_background: "#F0F4F4"
  adaptive_icon_foreground: "assets/images/logo/launcher_icon.png"
  background_color_ios: "#F0F4F4"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#F0F4F4" # Background color (same as your theme or brand color)
  image: assets/images/logo/launcher_icon.png # Splash image (should be centered and not full screen)
  android: true
  ios: true
  fullscreen: true

  # Optional (but recommended) settings:
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/images/logo/launcher_icon.png
    icon_background_color: "#F0F4F4"
    image_dark: assets/images/logo/launcher_icon.png
    icon_background_color_dark: "#F0F4F4"
